-- begin FIRESALES_PRODUCT
create unique index IDX_FIRESALES_PRODUCT_UK_NAME on FIRESALES_PRODUCT (NAME, DELETE_TS) ^
-- end FIRESALES_PRODUCT
-- begin FIRESALES_ORDER
alter table FIRESALES_ORDER add constraint FK_FIRESALES_ORDE_ON_CUSTOMER foreign key (CUSTOMER_ID) references FIRESALES_CUSTOMER(ID)^
alter table FIRESALES_ORDER add constraint FK_FIRESALES_ORDER_ON_PRODUCT foreign key (PRODUCT_ID) references FIRESALES_PRODUCT(ID)^
create index IDX_FIRESALES_ORDE_ON_CUST on FIRESALES_ORDER (CUSTOMER_ID)^
create index IDX_FIRESALES_ORDE_ON_PRODUCT on FIRESALES_ORDER (PRODUCT_ID)^
-- end FIRESALES_ORDER
